### ISSUE TITLE
Briana's feedback: round 5

### ISSUE THREAD

**Issue by brianamarie** [githubtraining/react-course#35]
Hi @partyshah - I'm going to make a list here. Some of the items are duplicates of previous feedback so I'm trying a different format.

- [x] Consistent punctuation in step description in config
- [x] Description of Readme
  - [x] git > Git
  - [x] Javascript > JavaScript
- [x] Activity: open a pull request - needs formatted, included in 1st step
  - [x] This should also be a short link that they just need to click
- [x] Step 2: "App.jsx" > "src/App.jsx"
- [x] Step 2: Do we need to save the file? Yes. Also in every step where they edit the file. 
- [ ] Template repository doesn't have descriptive commits - and it needs to
- [x] Step 2: "Added" > "Add", commits should be present tense
- [x] How to Talk to your Child
  - [x] Header is confusing, what does it mean? Too much jargon too soon
  - [x] Inconsistent capitalization
  - [x] Remove "Hmmmm" overly casual
  - [x] Definition of props should be somewhere here, clearly formatted so it sticks out. Same thing for the definition of components earlier on.
- [x] Step 3
  - [x] "List.jsx" > "src/List.jsx". Remove this sentence it makes it seem like the file we edit is List instead of App
  - [x] At the top? Which line? It's 3. Every single time we tell them to change a file it should say the line number. Apply this comment to every single response. Every single one.
  - [x] Import statement reference in the template repository is step 2 instead of 3
- [x] package-lock.json is sohwing as changed, we need to address that.
- [x] Step 4: "Now," > "Now"
- [x] If we're expected to keep the program running we should A) tell them how to exit, B) tell them explicitly when and why to open a 2nd window  
- [x] Step 4, #1: Which line?
- [x] Step 4: "App.jsx" > "src/App.jsx". Apply this logic to every single response also.
- [x] Step 4: Consistent punctuation at the end of steps
- [x] First push should be `git push -u origin changes`, and all subsequent pushes should just be `git push`
- [x] Step 4: Code explanation needs to go above activity and have a more specific title
- [x] Step 5: Include directory paths in file titles
- [x] Step 5, #1: Find a more concise way to say this step
- [ ] When replacing code, "{}" are confusing throughout in the template repository. Remove them.
- [x] Step 5 #3, wrong file listed to commit. 
- [x] Many pushes and commits seem to use the same commit message instead of actually being descriptive 
- [x] All: I'll respond after you push > after I detect a push > formatting also needs fixed to match template
- [x] "Content" as a header in one step still?
- [x] Content section: Typo in dynamic
- [x] Fix all occurrences: "Step 6 - sdfds" > "Step 6: sdfd" with a colon instead of a minus
- [x] Step 6: Which line? 
- [x] Step 6: We have them check for errors but don't tell them what to do if there are errors - what's the point of this step? Remove it if we don't give them more information on what to do.
- [x] Step 6: commit message isn't descriptive
- [x] "Explaining `this.setState`": First person "I" edit
- [x] 7: Which line?

At this point I stopped going through it because it felt like a lot of the feedback was repetitive. look forward to chatting about this @partyshah and seeing it implemented.
